### ISSUE TITLE
Advice：Increase macroMyKBD‘s speed

### ISSUE THREAD

**Issue by PotatoJet** [lal12/macroMyKBD#10]
I used to use TaranVH's HASU_USB and intercet.
https://github.com/TaranVH/2nd-keyboard
Now I'm using macroMyKBD to call AHK.However,I obviously feel macroMyKBD's speed is slower than QMK  and intercept.
I even recorded a video of these two methods,then compare them frame by frame on Premiere.
After a lot of data analysis,I find that macroMyKBD is 3.5 times slower than HASU_USB and intercet.
I hope that you can speed up macroMyKBD.

**Comment by lal12** [comment]
I don't wonder that mmkbd is slower, but I am surprised it is that noticeable. 

I wonder how you've measured it? Camera at keyboard and screen?

What kind of events and actions do you use? Maybe just attach your actions.yml and the used scripts (ahk?). 

I have the suspicion that starting another script/process for each keystroke might be the issue.

**Comment by PotatoJet** [comment]
Yes,Camera in slow motion mode at keyboard and screen.Even under normal condition, I can feel it's slower.

Yes,I starting another script/process for each keystroke.

actions.yml↓↓↓
```
devices:
  - name: 2nd_keyboard
    vendor: 0x1A2C
    prod: 0x2D43
    passthrough: false

  - name: 3rd_keyboard
    vendor: 0x1C4F
    prod: 0x0002
    passthrough: false

actions:
  - cmd: C:\Users\35375\Desktop\macroMyKBD\2nd_keyboard\lwin.ahk
    events: 
      - keys: [227]
        on: 'press'
        only: true
        device: 1

  - cmd: C:\Users\35375\Desktop\macroMyKBD\2nd_keyboard\lalt.ahk
    events: 
      - keys: [226]
        on: 'press'
        only: true
        device: 1
 


  - cmd: C:\Users\35375\Desktop\macroMyKBD\3rd_keyboard\lwin.ahk
    events: 
      - keys: [227]
        on: 'press'
        only: true
        device: 2

  - cmd: C:\Users\35375\Desktop\macroMyKBD\3rd_keyboard\lalt.ahk
    events: 
      - keys: [226]
        on: 'press'
        only: true
        device: 2
```


lwin.ahk↓↓↓
```
if WinActive("ahk_exe cloudmusic.exe")
{
send !{F4}	
}
else
{
run C:\App\CloudMusic\cloudmusic.exe
}
return
````


lalt.ahk↓↓↓
```
run notepad
```
