### ISSUE TITLE
How does macroMyKBD work with AutoHotKey?

### ISSUE THREAD

**Issue by PotatoJet** [lal12/macroMyKBD#2]

**Comment by lal12** [comment]
You should start it as any you would call any program from macroMyKBD. Put the following entry into the actions.yml, it should launch an AHK script when pressing windows key + C down. 

```YAML
- cmd: '"c:\program files (x86)\autohotkey\autohotkey.exe" "c:\path\to\my\autohotkey\script.ahk"'
  events: 
    - keys: [227, 6]
      on: 'down'
      only: true
      device: 1
```

Look into the included example [actions.yml](/lal12/macroMyKBD/blob/master/actions.yml) to see the whole structure. To ensure that it works with spaces you need to wrap the paths into double quotes, to prevent troubles the whole command then should be wrapped in single quotes.
