### ISSUE TITLE
How to add 3rd 4th keyboard?

### ISSUE THREAD

**Issue by PotatoJet** [lal12/macroMyKBD#9]
@KGT1 @lal12 Please help me

**Comment by lal12** [comment]
You have to look up the vendor id and the device id of your keyboard. This process is shown in the [video tutorial at 0:53](https://youtu.be/k5ltJ_6T3qI?t=53). You have to repeat the step for each keyboard you want to control.

Keep in mind that multiple keyboard of the same model currently are not really supported so better use 4 different models.

Now you have to replace the devices section in the `actions.yml` file. The basic process is also shown in the video, but now you have to do it for each keyboard. So after replacing the device section below, you have to add the previously looked up ids to the different devices.

```yml
devices:
  - name: My second keyboard
    vendor: 0x4d9
    prod: 0x1604
    passthrough: false
  - name: My third keyboard
    vendor: 0x4d9
    prod: 0x1606
    passthrough: false
  - name: My fourth keyboard
    vendor: 0x4d9
    prod: 0x1607
    passthrough: false
```

As you can see each of those entries describes one keyboard, so you can add as many as you like if you just copy one entry (see the snippet below) and paste it below the last device (before the actions section). E.g. of just a single device config:
```yml
  - name: My 5th keyboard
    vendor: 0x4d9
    prod: 0x1609
    passthrough: false
```
To link an action with a keyboard you simply have to use the index of the keyboard in the list above, in this case "My second keyboard" would be no 1, and "my fourth keyboard" would be no 3.

So to call a program when releasing the `A` key on "My third keyboard" and another program on pressing down the 'B' key on  "My second keyboard", the following snippet is needed:

```yml
actions:
  - cmd: 'myprogram1'
    events: 
      - keys: [4] # a key
        on: 'up'
        only: true
        device: 2
  - cmd: 'start cmd.exe' 
    events: 
      - keys: [5] # b key
        on: 'down'
        only: true
        device: 1
```

I hope this was understandable. If not feel free to ask again ;).

Btw I am currently working on an UI for macroMyKBD, maybe I can release it the next days.
